name: ContinousDelivery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: npm install 
        run: npm install
      - name: export cv to html
        run: make generate-html
      - name: spell check
        run: make spell-check
      - name: prepare github-pages folder
        run: make prepare-github-pages
      - name: Deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: github-pages
          folder: github-pages